# Generated by Django 3.2.3 on 2021-06-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maininfo',
            options={'verbose_name_plural': 'Main Info'},
        ),
        migrations.RenameField(
            model_name='maininfo',
            old_name='fact',
            new_name='fax',
        ),
        migrations.AddField(
            model_name='maininfo',
            name='age_from',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='age_to',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='partner_hotel',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='partner_hotel_distance_unit',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='pets_charges',
            field=models.CharField(blank=True, choices=[(None, None), ('Inclusive', 'Inclusive'), ('Against Charge', 'Against Charge')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='pets_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='pets_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='resort_charges',
            field=models.CharField(blank=True, choices=[(None, None), ('Inclusive', 'Inclusive'), ('Against Charge', 'Against Charge')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='resort_charges_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='resort_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='resort_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='accommodation_type',
            field=models.CharField(choices=[('Resort', 'Resort'), ('Hotel', 'Hotel'), ('Motel', 'Motel'), ('Villa', 'Villa'), ('Apartment', 'Apartment')], default='Hotel', max_length=150),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='charges_person_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='child_charges',
            field=models.CharField(blank=True, choices=[(None, None), ('Inclusive', 'Inclusive'), ('Against Charge', 'Against Charge')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='child_charges_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='child_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='deposit_required_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='partner_hotel_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='tax_charges',
            field=models.CharField(blank=True, choices=[(None, None), ('Inclusive', 'Inclusive'), ('Against Charge', 'Against Charge')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='tax_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='tourist_charges',
            field=models.CharField(blank=True, choices=[(None, None), ('Inclusive', 'Inclusive'), ('Against Charge', 'Against Charge')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='tourist_charges_person_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='tourist_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
