# Generated by Django 3.2.3 on 2021-07-20 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20210713_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='user',
        ),
        migrations.DeleteModel(
            name='MainInfo',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
