# Generated by Django 3.2.3 on 2021-07-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_category_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='location_name',
            new_name='picture_name',
        ),
    ]
