# Generated by Django 3.2.3 on 2021-07-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_rename_location_name_project_picture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
