# Generated by Django 3.2.3 on 2021-07-27 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_project_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
