# Generated by Django 3.2.3 on 2021-08-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_project_show_in_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Main Categories',
            },
        ),
    ]
