from rest_framework import serializers


class SurveySerializer(serializers.Serializer):
    chandeliers1 = serializers.BooleanField()
    chandeliers2 = serializers.BooleanField()
    chandeliers3 = serializers.BooleanField()
    chandeliers4 = serializers.BooleanField()
    colorMix = serializers.BooleanField()
    colorScheme = serializers.CharField(max_length=50, allow_null=True)
    comments = serializers.CharField(max_length=250, allow_null=True)
    designType = serializers.CharField(max_length=50, allow_null=True)
    directLight = serializers.BooleanField()
    email = serializers.EmailField()
    glass = serializers.BooleanField()
    indirectLight = serializers.BooleanField()
    lightingLevel = serializers.CharField(max_length=50, allow_null=True)
    marbleGranite = serializers.BooleanField()
    metal = serializers.BooleanField()
    name = serializers.CharField(max_length=150)
    pattern = serializers.CharField(max_length=50, allow_null=True)
    patternMix = serializers.BooleanField()
    phone = serializers.CharField(max_length=15)
    projectType = serializers.CharField(max_length=50)
    spotLight1 = serializers.BooleanField()
    spotLight2 = serializers.BooleanField()
    spotLight3 = serializers.BooleanField()
    spotLight4 = serializers.BooleanField()
    stone = serializers.BooleanField()
    textureMaterialMix = serializers.BooleanField()
    wood = serializers.BooleanField()
    woodenLight1 = serializers.BooleanField()
    woodenLight2 = serializers.BooleanField()
    restaurantType = serializers.CharField(max_length=50, allow_null=True)
    designClass = serializers.CharField(max_length=50, allow_null=True)
    light = serializers.BooleanField(allow_null=True)
    waterFeatures = serializers.BooleanField(allow_null=True)
    seats = serializers.BooleanField(allow_null=True)


class ContactSerializer(serializers.Serializer):
    name = serializers.CharField(max_length=100)
    email = serializers.EmailField()
    subject = serializers.CharField(max_length=200)
    message = serializers.CharField(max_length=300)
